import {
	CheckOutlined,
	CopyOutlined,
	LeftOutlined,
	ReloadOutlined,
	RightOutlined,
} from "@ant-design/icons";
import { useCallback, useState } from "react";
import { pvMessage } from "@/admin/components/ui";

// Shared per-message chrome for both the standalone /chat page and the chat dock.

// ChatGPT-style action row under a finished assistant message: copy the reply,
// "try again" (regenerate as a branch), and the model that produced it. `leading`
// lets the caller slot the branch switcher in front of the icons.
export function MessageActions({
	text,
	modelLabel,
	canRetry,
	onRetry,
	leading,
}) {
	const [copied, setCopied] = useState(false);
	const copy = useCallback(async () => {
		try {
			await navigator.clipboard.writeText(text || "");
			setCopied(true);
			setTimeout(() => setCopied(false), 1400);
		} catch {
			pvMessage.error("Couldn't copy to clipboard");
		}
	}, [text]);
	return (
		<div className="chatx-msg-actions">
			{leading}
			<button
				type="button"
				className="chatx-msg-action"
				onClick={copy}
				title="Copy response"
				aria-label="Copy response"
			>
				{copied ? <CheckOutlined /> : <CopyOutlined />}
			</button>
			{canRetry ? (
				<button
					type="button"
					className="chatx-msg-action"
					onClick={onRetry}
					title="Try again"
					aria-label="Regenerate response"
				>
					<ReloadOutlined />
				</button>
			) : null}
			{modelLabel ? (
				<span className="chatx-msg-model" title={`Generated by ${modelLabel}`}>
					{modelLabel}
				</span>
			) : null}
		</div>
	);
}

// ‹ n/n › fork switcher, shown on any message at a branch point (parent has >1
// child). Steps through siblings by id via the caller's handlers.
export function BranchSwitcher({ index, count, onPrev, onNext }) {
	if (!count || count < 2) return null;
	return (
		<span className="chatx-branch">
			<button
				type="button"
				className="chatx-branch-arrow"
				onClick={onPrev}
				disabled={index <= 1}
				aria-label="Previous branch"
				title="Previous version"
			>
				<LeftOutlined />
			</button>
			<span className="chatx-branch-count">
				{index}/{count}
			</span>
			<button
				type="button"
				className="chatx-branch-arrow"
				onClick={onNext}
				disabled={index >= count}
				aria-label="Next branch"
				title="Next version"
			>
				<RightOutlined />
			</button>
		</span>
	);
}
