import {
	BookOutlined,
	CloudOutlined,
	DatabaseOutlined,
	RocketOutlined,
	SafetyOutlined,
	SearchOutlined,
	ShareAltOutlined,
	ThunderboltOutlined,
} from "@ant-design/icons";
import { PageContent } from "../../components/layout/PageLayout";
import { PvButton, PvPanel } from "../../components/ui";
import "../../vault-pixel.css";
import "./homepage.css";

const FEATURES = [
	{
		icon: <BookOutlined />,
		title: "Markdown Notes",
		tag: "Notes",
		description:
			"A fast, folder-and-tag organized note vault with rich Markdown editors (BlockNote & Milkdown), tabs, and live updates over SSE.",
	},
	{
		icon: <SearchOutlined />,
		title: "Hybrid Search",
		tag: "FTS + pgvector",
		description:
			"Full-text + trigram + vector search fused with reciprocal-rank fusion. Embeddings are generated by a background worker via Azure OpenAI.",
	},
	{
		icon: <SafetyOutlined />,
		title: "Secure Access",
		tag: "JWT + OTP + API keys",
		description:
			"JWT (RS256) auth with refresh tokens, TOTP two-factor, trusted devices, and scoped API keys for programmatic access.",
	},
	{
		icon: <ShareAltOutlined />,
		title: "Shareable Links",
		tag: "Shares",
		description:
			"Publish any note behind a public slug with optional password and expiry, in read-only or editable mode — no account required to view.",
	},
	{
		icon: <CloudOutlined />,
		title: "File Storage",
		tag: "Bunny CDN",
		description:
			"Attach images and files to notes, served straight from a Bunny S3-compatible CDN with signed URLs — bytes never round-trip the backend.",
	},
	{
		icon: <ThunderboltOutlined />,
		title: "Rust Backend",
		tag: "Actix-web",
		description:
			"Actix-web + sqlx (compile-time-checked SQL) on PostgreSQL 15 with pgvector, plus a dedicated embedding worker. Lean and fast.",
	},
];

const TECH_STACK = [
	"React 19",
	"Ant Design",
	"Vite",
	"Rust",
	"Actix-web",
	"PostgreSQL",
	"pgvector",
	"Nginx",
	"Docker",
];

const Homepage = () => {
	return (
		<PageContent>
			{/* Hero */}
			<div className="vp-home-hero">
				<h1 className="vp-home-hero-title">Piuma Vault</h1>
				<p className="vp-home-hero-sub">
					A feather-light, self-hosted notes vault — Markdown notes with hybrid
					full-text & vector search, shareable links, and file storage, on a
					lean Rust + React stack.
				</p>
				<div className="vp-home-cta">
					<PvButton variant="primary" href="/" icon={<BookOutlined />}>
						Open the Vault
					</PvButton>
					<PvButton to="/admin/about" icon={<SearchOutlined />}>
						About
					</PvButton>
				</div>
			</div>

			{/* Tech stack */}
			<p className="vp-home-stack-label">Built with</p>
			<div className="vp-home-tags">
				{TECH_STACK.map((tech) => (
					<span key={tech} className="vp-tag">
						{tech}
					</span>
				))}
			</div>

			{/* Features */}
			<div className="vp-home-section-head">
				<h2 className="vp-h2">What's inside</h2>
				<p className="vp-muted vp-text">
					Everything the vault does — and nothing it doesn't.
				</p>
			</div>
			<div className="vp-grid">
				{FEATURES.map((feature) => (
					<div className="vp-card" key={feature.title}>
						<div className="vp-home-feature-icon">{feature.icon}</div>
						<h3 className="vp-card-title">{feature.title}</h3>
						<span
							className="vp-tag vp-tag--accent"
							style={{ marginBottom: 10 }}
						>
							{feature.tag}
						</span>
						<p className="vp-card-desc" style={{ marginTop: 10 }}>
							{feature.description}
						</p>
					</div>
				))}
			</div>

			{/* Closing */}
			<PvPanel title="piuma — feather" className="vp-home-closing-panel">
				<div className="vp-home-closing">
					<div className="vp-home-closing-icon">
						<RocketOutlined />
					</div>
					<h3 className="vp-h2">Feather-light by design</h3>
					<p className="vp-home-closing-text">
						<strong className="vp-accent">piuma</strong> means "feather" — a
						vault that stays out of your way: just your notes, search, sharing,
						and storage. No bloat, fully self-hosted, yours to run.
					</p>
					<div className="vp-home-tags">
						<span className="vp-tag vp-tag--blue">
							<DatabaseOutlined /> pgvector search
						</span>
						<span className="vp-tag vp-tag--green">
							<SafetyOutlined /> self-hosted
						</span>
						<span className="vp-tag vp-tag--accent">
							<CloudOutlined /> CDN-backed files
						</span>
					</div>
				</div>
			</PvPanel>
		</PageContent>
	);
};

export default Homepage;
