import { Dimensions, StyleSheet } from "react-native";
import { colors, mono as MONO } from "../../utils/theme";

// Cap the task sheet's scrollable body so an expanded editor never pushes it
// off the top of the screen — it scrolls within this height instead.
export const SHEET_MAX = Math.round(Dimensions.get("window").height * 0.68);

export const s = StyleSheet.create({
	root: { flex: 1, backgroundColor: colors.bg },
	header: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingHorizontal: 16,
		paddingVertical: 12,
		borderBottomWidth: 1,
		borderBottomColor: colors.border,
	},
	headerRight: { flexDirection: "row", alignItems: "center", gap: 16 },
	title: {
		color: colors.text,
		fontFamily: MONO,
		fontSize: 16,
		fontWeight: "700",
		letterSpacing: 1,
	},
	chipBar: {
		borderBottomWidth: 1,
		borderBottomColor: colors.border,
	},
	tagSearchRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		marginHorizontal: 16,
		marginTop: 10,
		paddingHorizontal: 10,
		borderWidth: 1,
		borderColor: colors.border,
		backgroundColor: colors.bgSoft,
	},
	tagSearch: {
		flex: 1,
		color: colors.text,
		fontFamily: MONO,
		fontSize: 13,
		paddingVertical: 7,
	},
	chipRow: {
		flexDirection: "row",
		gap: 6,
		paddingHorizontal: 16,
		paddingVertical: 10,
	},
	chipRowSub: {
		paddingTop: 0,
		paddingBottom: 10,
	},
	chip: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		borderWidth: 1,
		borderColor: colors.border,
		backgroundColor: colors.bgSoft,
		paddingHorizontal: 10,
		paddingVertical: 6,
	},
	chipOn: { borderColor: colors.accent2, backgroundColor: colors.bg },
	// Icon-only chip that reveals the tag-search field.
	searchChip: {
		justifyContent: "center",
		alignItems: "center",
		borderWidth: 1,
		borderColor: colors.border,
		backgroundColor: colors.bgSoft,
		paddingHorizontal: 9,
		paddingVertical: 6,
	},
	chipText: { color: colors.text, fontFamily: MONO, fontSize: 12 },
	// Bucket label reads as a heading (colour lives in the swatch).
	chipTextBucket: {
		fontWeight: "700",
		textTransform: "uppercase",
		letterSpacing: 0.4,
	},
	// Filled square = bucket colour; hollow (border only) = "no bucket".
	chipSwatch: {
		width: 10,
		height: 10,
		borderRadius: 2,
		borderWidth: 1,
		borderColor: colors.muted,
		backgroundColor: "transparent",
	},
	chipTextOn: { color: colors.accent2 },
	chipCount: { color: colors.muted, fontFamily: MONO, fontSize: 11 },
	// The dragger's outer container must fill the space left under the header +
	// chip bar so its FlatList scrolls within bounds (see usage comment).
	listContainer: { flex: 1 },
	listFlex: { flex: 1 },
	scroll: { padding: 16, paddingBottom: 48 },
	// Footer button revealing the next page of completed tasks.
	loadMore: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 8,
		paddingVertical: 12,
		marginTop: 2,
	},
	loadMoreText: {
		color: colors.muted,
		fontFamily: MONO,
		fontSize: 12,
		letterSpacing: 0.5,
	},
	section: {
		color: colors.muted,
		fontFamily: MONO,
		fontSize: 11,
		fontWeight: "700",
		letterSpacing: 1.5,
		textTransform: "uppercase",
		marginTop: 16,
		marginBottom: 8,
	},
	// Active bucket/tag filter shown above the groups.
	filterHeading: {
		color: colors.accent2,
		fontFamily: MONO,
		fontSize: 12,
		fontWeight: "700",
		letterSpacing: 0.5,
		marginTop: 4,
		marginBottom: 2,
	},
	recHead: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
	},
	addRec: {
		color: colors.accent2,
		fontFamily: MONO,
		fontSize: 12,
		fontWeight: "700",
		letterSpacing: 0.5,
		marginTop: 16,
	},
	empty: {
		color: colors.muted,
		fontFamily: MONO,
		fontStyle: "italic",
		fontSize: 12,
		padding: 4,
	},
	// Card holds two stacked lines (meta on top, title below).
	taskRow: {
		backgroundColor: colors.bgSoft,
		borderWidth: 1,
		borderColor: colors.border,
		// Thicker left edge carries the task's priority colour (see PRIORITY_*).
		borderLeftWidth: 3,
		// Square edges = pixel.
		paddingHorizontal: 10,
		paddingVertical: 8,
		marginBottom: 6,
	},
	// Completed rows stay single-line (checkbox + strikethrough title).
	taskRowInline: { flexDirection: "row", alignItems: "center", gap: 10 },
	// Top line of an active card: checkbox + bucket/due cluster + tags (right).
	taskTop: { flexDirection: "row", alignItems: "center", gap: 8 },
	// Row lifted while being dragged.
	taskRowActive: {
		borderColor: colors.accent2,
		backgroundColor: colors.bg,
		shadowColor: "#000",
		shadowOpacity: 0.4,
		shadowRadius: 8,
		shadowOffset: { width: 0, height: 4 },
		elevation: 6,
	},
	dim: { opacity: 0.55 },
	check: { color: colors.accent2, fontFamily: MONO, fontSize: 18 },
	// Match the ☐ glyph footprint so swapping in the spinner doesn't shift the row.
	checkSpin: { width: 18, height: 18 },
	taskMain: { flex: 1 },
	taskTitle: {
		color: colors.text,
		fontFamily: MONO,
		fontSize: 15,
		lineHeight: 20,
	},
	// Title on its own line under the meta row.
	taskTitleRow: { marginTop: 6 },
	strike: { textDecorationLine: "line-through", flex: 1 },
	// Meta line: bucket+due cluster on the left, tags right-aligned.
	metaRow: {
		flexDirection: "row",
		alignItems: "flex-start",
		gap: 8,
		marginTop: 4,
	},
	metaLeft: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		flexShrink: 1,
		minWidth: 0,
	},
	tagsRight: {
		flex: 1,
		flexDirection: "row",
		flexWrap: "wrap",
		justifyContent: "flex-end",
		gap: 8,
	},
	meta: { fontFamily: MONO, fontSize: 11, letterSpacing: 0.3 },
	due: { color: colors.accent },
	// Overdue due-date text reads in the alert colour.
	dueOverdue: { color: colors.accent3, fontWeight: "700" },
	// Bell shown when a task has one or more alerts configured.
	alertIcon: { marginLeft: 2 },
	tag: { color: colors.accent2 },
	rrule: { color: colors.accent4 },
	metaSep: { color: colors.muted },
	// Bucket on the meta line: a colour swatch + uppercase name (colour lives in
	// the swatch), matching the filter chips / web sidebar.
	bucketTag: {
		flexDirection: "row",
		alignItems: "center",
		gap: 5,
		flexShrink: 1,
		minWidth: 0,
	},
	bucketSwatch: {
		width: 8,
		height: 8,
		borderRadius: 2,
		borderWidth: 1,
		borderColor: colors.muted,
		backgroundColor: "transparent",
	},
	bucketName: {
		color: colors.muted,
		textTransform: "uppercase",
		letterSpacing: 0.5,
		flexShrink: 1,
	},
	// Forms
	form: { paddingHorizontal: 16, paddingTop: 2, gap: 4 },
	label: {
		color: colors.muted,
		fontFamily: MONO,
		fontSize: 11,
		fontWeight: "700",
		letterSpacing: 1,
		textTransform: "uppercase",
		marginTop: 5,
	},
	input: {
		backgroundColor: colors.bg,
		borderWidth: 1,
		borderColor: colors.border,
		color: colors.text,
		fontFamily: MONO,
		paddingHorizontal: 10,
		paddingVertical: 7,
		fontSize: 14,
	},
	// Scrollable detail body: capped so an expanded editor scrolls instead of
	// shoving the sheet off-screen.
	sheetScroll: { maxHeight: SHEET_MAX },
	// Header: checkbox + bucket tag (left) + priority flag (right).
	headerRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 10,
		marginBottom: 10,
	},
	headerLeft: {
		flexDirection: "row",
		alignItems: "center",
		gap: 9,
		flexShrink: 1,
		minWidth: 0,
	},
	headerActions: { flexDirection: "row", alignItems: "center", gap: 4 },
	headerCheck: { fontFamily: MONO, fontSize: 22, lineHeight: 24 },
	// Match the ☐ glyph footprint so the spinner doesn't shift the row.
	headerCheckSpin: { width: 22, height: 24 },
	bucketChip: {
		flexDirection: "row",
		alignItems: "center",
		gap: 7,
		flexShrink: 1,
		borderWidth: 1,
		borderColor: colors.border,
		backgroundColor: colors.bgSoft,
		paddingHorizontal: 10,
		paddingVertical: 6,
	},
	flagBtn: { padding: 4 },
	// Priority popover anchored under the header flag.
	overlay: { ...StyleSheet.absoluteFillObject },
	menuBackdrop: { ...StyleSheet.absoluteFillObject },
	prioMenu: {
		// Drops from just under the header flag (header sits below the ~33px grab
		// zone; the flag is the top-right of the first row).
		position: "absolute",
		top: 56,
		right: 0,
		minWidth: 130,
		backgroundColor: colors.panel,
		borderWidth: 1,
		borderColor: colors.borderStrong,
		paddingVertical: 2,
		elevation: 8,
		shadowColor: "#000",
		shadowOpacity: 0.4,
		shadowRadius: 8,
		shadowOffset: { width: 0, height: 3 },
	},
	prioMenuItem: {
		flexDirection: "row",
		alignItems: "center",
		gap: 9,
		paddingHorizontal: 12,
		paddingVertical: 9,
	},
	prioMenuText: {
		flex: 1,
		color: colors.text,
		fontFamily: MONO,
		fontSize: 13,
		letterSpacing: 0.5,
		textTransform: "uppercase",
	},
	prioMenuTextOn: { color: colors.accent2, fontWeight: "700" },
	bucketChipText: {
		color: colors.text,
		fontFamily: MONO,
		fontSize: 12,
		fontWeight: "700",
		letterSpacing: 0.4,
		textTransform: "uppercase",
		flexShrink: 1,
	},
	// A row in the bucket picker sheet.
	bucketOpt: {
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
		paddingVertical: 12,
		borderTopWidth: 1,
		borderTopColor: colors.border,
	},
	bucketOptFirst: { borderTopWidth: 0 },
	bucketOptText: {
		flex: 1,
		color: colors.text,
		fontFamily: MONO,
		fontSize: 14,
		letterSpacing: 0.3,
	},
	titleDone: { color: colors.muted, textDecorationLine: "line-through" },
	// Borderless description below the title (TickTick-style plain notes).
	notesInput: {
		color: colors.muted,
		fontFamily: MONO,
		fontSize: 13,
		lineHeight: 19,
		minHeight: 36,
		paddingTop: 4,
		paddingBottom: 4,
	},
	// Borderless like the notes, but bigger + bold so it reads as the title.
	titleInput: {
		color: colors.text,
		fontFamily: MONO,
		fontSize: 19,
		lineHeight: 26,
		fontWeight: "700",
		minHeight: 38,
		paddingTop: 2,
		paddingBottom: 2,
	},
	// TickTick-style attribute row + inline accordion editor.
	attr: { borderTopWidth: 1, borderTopColor: colors.border },
	attrFlush: { borderTopWidth: 0 },
	attrHead: {
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
		paddingVertical: 12,
	},
	attrLabel: {
		color: colors.text,
		fontFamily: MONO,
		fontSize: 13,
		fontWeight: "700",
		letterSpacing: 0.5,
	},
	attrValWrap: {
		flex: 1,
		flexDirection: "row",
		justifyContent: "flex-end",
	},
	attrVal: {
		color: colors.muted,
		fontFamily: MONO,
		fontSize: 13,
		flexShrink: 1,
		textAlign: "right",
	},
	prioRow: { flexDirection: "row", gap: 6, flexWrap: "wrap" },
	prioBtn: {
		borderWidth: 1,
		borderColor: colors.border,
		paddingHorizontal: 14,
		paddingVertical: 7,
		backgroundColor: colors.bg,
	},
	prioBtnOn: { backgroundColor: colors.accent, borderColor: colors.accent },
	prioBtnText: {
		color: colors.text,
		fontFamily: MONO,
		fontSize: 12,
		letterSpacing: 0.5,
		textTransform: "uppercase",
	},
	prioBtnTextOn: { color: "#000", fontWeight: "700" },
	dowRow: { flexDirection: "row", gap: 6 },
	dowBtn: {
		width: 36,
		height: 36,
		borderWidth: 1,
		borderColor: colors.border,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: colors.bg,
	},
	dowBtnOn: { backgroundColor: colors.accent2, borderColor: colors.accent2 },
	dowText: { color: colors.muted, fontFamily: MONO, fontSize: 13 },
	dowTextOn: { color: "#000", fontWeight: "700" },
	hint: {
		color: colors.muted,
		fontFamily: MONO,
		fontSize: 11,
		letterSpacing: 0.5,
		marginTop: 4,
	},
	saveBtn: {
		backgroundColor: colors.accent,
		borderWidth: 2,
		borderColor: colors.accent,
		paddingVertical: 9,
		alignItems: "center",
		marginTop: 10,
	},
	saveBtnText: {
		color: "#000",
		fontFamily: MONO,
		fontWeight: "700",
		fontSize: 14,
		letterSpacing: 1.5,
		textTransform: "uppercase",
	},
	btnDisabled: { opacity: 0.6 },
});
