import {
	CheckOutlined,
	CopyOutlined,
	DownOutlined,
	ReloadOutlined,
} from "@ant-design/icons";
import {
	useCallback,
	useEffect,
	useLayoutEffect,
	useMemo,
	useRef,
	useState,
} from "react";
import { useNavigate } from "react-router-dom";
import { pvMessage } from "@/admin/components/ui";
import {
	clearConversation,
	createConversation,
	fetchAllModels,
	fetchConversation,
	injectMessage,
	retitleConversation,
	stopConversation,
	streamChat,
	updateConversation,
} from "../../api/agentChatApi";
import { uploadChatImage } from "../../api/storage";
import { useAgentList, useDefaultAgent } from "../../queries";
import { formatDateTime, timeAgo } from "../../utils/dateTime";
import SpriteRunner from "../SpriteRunner";
import {
	AssistantBubble,
	appendTextPart,
	blocksToImages,
	blocksToParts,
	blocksToText,
	newMessageId,
	partsToText,
	UserBubble,
} from "./messageUtils";

// Universal client commands (same for every agent). Agent-specific commands are
// the prompt macros from the agent profile, merged in at render time.
const CLIENT_COMMANDS = [
	{ name: "new", description: "Start a new conversation" },
	{ name: "clear", description: "Wipe this conversation's messages" },
	{ name: "sessions", description: "Toggle the conversation list" },
	{ name: "models", description: "Pick the model for this chat" },
	{ name: "title", description: "Rename this conversation" },
];

// The two options shown after `/title`.
const TITLE_ACTIONS = [
	{
		key: "auto",
		label: "Auto-rename with AI",
		desc: "Generate a title from the conversation",
	},
	{ key: "manual", label: "Edit manually", desc: "Type a new title yourself" },
];

// ChatGPT-style action row under each finished assistant message: copy the reply
// to the clipboard, "try again" (regenerate — last message only), and the model
// that produced it for visibility.
function MessageActions({ text, modelLabel, canRetry, onRetry }) {
	const [copied, setCopied] = useState(false);
	const copy = useCallback(async () => {
		try {
			await navigator.clipboard.writeText(text || "");
			setCopied(true);
			setTimeout(() => setCopied(false), 1400);
		} catch {
			pvMessage.error("Couldn't copy to clipboard");
		}
	}, [text]);
	return (
		<div className="chatx-msg-actions">
			<button
				type="button"
				className="chatx-msg-action"
				onClick={copy}
				title="Copy response"
				aria-label="Copy response"
			>
				{copied ? <CheckOutlined /> : <CopyOutlined />}
			</button>
			{canRetry ? (
				<button
					type="button"
					className="chatx-msg-action"
					onClick={onRetry}
					title="Try again"
					aria-label="Regenerate response"
				>
					<ReloadOutlined />
				</button>
			) : null}
			{modelLabel ? (
				<span className="chatx-msg-model" title={`Generated by ${modelLabel}`}>
					{modelLabel}
				</span>
			) : null}
		</div>
	);
}

// Center column: the conversation itself. Loads `conversationId` (null = a fresh
// chat), streams turns, renders tools inline, and exposes a header model picker.
// Lifts a freshly-created conversation id + any list-affecting change up to the
// page so the sidebar stays in sync.
export default function ChatConversation({
	conversationId,
	onConversationCreated,
	onConversationsChanged,
	onToggleSidebar,
	onNewChat,
}) {
	const navigate = useNavigate();
	const { data: agents = [] } = useAgentList();
	const { data: def } = useDefaultAgent();
	const effectiveAgent = def?.agent || "vault_agent";
	const agentLabel =
		agents.find((a) => a.kind === effectiveAgent)?.display_name || "Piuma";

	const [messages, setMessages] = useState([]);
	const [input, setInput] = useState("");
	const [isStreaming, setIsStreaming] = useState(false);
	const [sending, setSending] = useState(false);
	const [loadingConv, setLoadingConv] = useState(false);
	const [title, setTitle] = useState(null);
	// { created_at, updated_at } of the loaded conversation, for the header line.
	const [meta, setMeta] = useState(null);

	// The model bound to the conversation (or null → backend default).
	const [modelId, setModelId] = useState(null);
	const [allModels, setAllModels] = useState([]);
	const [modelMenuOpen, setModelMenuOpen] = useState(false);

	// Images staged for the next turn.
	const [pendingImages, setPendingImages] = useState([]);

	// Slash-command menu (client commands + the agent's macros) and the `/title`
	// two-option submenu.
	const [slashActive, setSlashActive] = useState(0);
	const [titleMenu, setTitleMenu] = useState(false);
	const [titleActive, setTitleActive] = useState(0);

	// The conversation actually loaded/displayed, as a ref. Async writers bail if
	// the user switched away, and the load effect uses it to tell an EXTERNAL
	// switch (sidebar / new-chat) apart from the id we mint ourselves mid-send —
	// the latter must NOT reset the live stream. Seeded null so the first real id
	// (mount restore) still loads.
	const convRef = useRef(null);

	const scrollRef = useRef(null);
	const abortRef = useRef(null);
	const inputRef = useRef(null);
	const fileRef = useRef(null);
	const atBottomRef = useRef(true);
	const [showJump, setShowJump] = useState(false);

	const focusInput = useCallback(() => {
		requestAnimationFrame(() => inputRef.current?.focus());
	}, []);

	// Single navigation entry point for chat links / "Go" actions.
	const goTo = useCallback(
		(to) => {
			if (!to) return;
			if (/^https?:\/\//i.test(to)) {
				window.open(to, "_blank", "noopener,noreferrer");
				return;
			}
			if (to.startsWith("/")) navigate(to);
		},
		[navigate],
	);

	// ── Load / reset on EXTERNAL conversation switch ────────────────────────────
	useEffect(() => {
		// Ignore the prop catching up to an id we just created ourselves (mid-send);
		// resetting here would kill the stream that's still writing into the bubble.
		if (conversationId === convRef.current) return;
		convRef.current = conversationId;
		abortRef.current?.abort();
		abortRef.current = null;
		setIsStreaming(false);
		setInput("");
		setMessages([]);
		setModelId(null);
		setTitle(null);
		setMeta(null);
		if (!conversationId) {
			setLoadingConv(false);
			return;
		}
		let cancelled = false;
		setLoadingConv(true);
		fetchConversation(conversationId)
			.then((d) => {
				if (cancelled) return;
				setModelId(d.conversation?.model_id || null);
				setTitle(d.conversation?.title || null);
				setMeta({
					created_at: d.conversation?.created_at || null,
					updated_at: d.conversation?.updated_at || null,
				});
				setMessages(
					(d.messages || []).map((m) => ({
						id: m.id,
						role: m.role,
						content: blocksToText(m.content),
						parts: blocksToParts(m.content),
						images: blocksToImages(m.content),
						model: m.model_used || null,
					})),
				);
			})
			.catch(() => {})
			.finally(() => {
				if (!cancelled) setLoadingConv(false);
				focusInput();
			});
		return () => {
			cancelled = true;
		};
	}, [conversationId, focusInput]);

	// Model catalog (for the picker + vision gating).
	useEffect(() => {
		fetchAllModels()
			.then(setAllModels)
			.catch(() => {});
	}, []);

	const activeModel = useMemo(() => {
		if (!allModels.length) return null;
		return modelId
			? allModels.find((m) => m.id === modelId)
			: allModels.find((m) => m.is_default);
	}, [allModels, modelId]);
	const visionEnabled = !!activeModel?.supports_vision;
	// The active model, as a ref, so the stream's onDone can stamp the model onto
	// the just-streamed assistant message without re-creating the handlers.
	const activeModelRef = useRef(activeModel);
	useEffect(() => {
		activeModelRef.current = activeModel;
	}, [activeModel]);

	// Resolve a message's stored model (`model_used`, a wire id) to a friendly
	// display name via the model catalog; fall back to the raw value.
	const modelLabelFor = useCallback(
		(m) => {
			if (!m?.model) return null;
			const hit = allModels.find(
				(x) => x.model_id === m.model || x.id === m.model,
			);
			return hit?.display_name || m.model;
		},
		[allModels],
	);

	// ── Scroll handling (stick-to-bottom) ──────────────────────────────────────
	const handleScroll = useCallback(() => {
		const el = scrollRef.current;
		if (!el) return;
		const atBottom = el.scrollHeight - (el.scrollTop + el.clientHeight) < 80;
		atBottomRef.current = atBottom;
		setShowJump((p) => (p === !atBottom ? p : !atBottom));
	}, []);
	const scrollToBottom = useCallback(() => {
		atBottomRef.current = true;
		setShowJump(false);
		const el = scrollRef.current;
		if (el) el.scrollTop = el.scrollHeight;
	}, []);

	// biome-ignore lint/correctness/useExhaustiveDependencies: scroll on new messages
	useEffect(() => {
		if (!atBottomRef.current || !scrollRef.current) return;
		scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
	}, [messages]);

	// Auto-grow the textarea up to its max-height.
	// biome-ignore lint/correctness/useExhaustiveDependencies: re-measure on text change
	useLayoutEffect(() => {
		const el = inputRef.current;
		if (!el) return;
		el.style.height = "auto";
		el.style.height = `${el.scrollHeight}px`;
	}, [input]);

	useEffect(() => () => abortRef.current?.abort(), []);

	// ── Images ─────────────────────────────────────────────────────────────────
	const uploadingImages = pendingImages.some((p) => p.status === "uploading");

	const removePendingImage = useCallback((id) => {
		setPendingImages((curr) => {
			const hit = curr.find((p) => p.id === id);
			if (hit?.localUrl) URL.revokeObjectURL(hit.localUrl);
			return curr.filter((p) => p.id !== id);
		});
	}, []);

	const addImageFile = useCallback(
		(file) => {
			if (!file?.type?.startsWith("image/")) return;
			if (!visionEnabled) {
				pvMessage.info(
					"This model can't read images — switch to a vision model first.",
				);
				return;
			}
			const id = newMessageId();
			const localUrl = URL.createObjectURL(file);
			const probe = new Image();
			probe.onload = () =>
				setPendingImages((curr) =>
					curr.map((p) =>
						p.id === id
							? { ...p, w: probe.naturalWidth, h: probe.naturalHeight }
							: p,
					),
				);
			probe.src = localUrl;
			setPendingImages((curr) => [
				...curr,
				{
					id,
					localUrl,
					url: null,
					key: null,
					mediaType: file.type || "image/png",
					name: file.name || "image.png",
					w: 0,
					h: 0,
					status: "uploading",
				},
			]);
			uploadChatImage({ file, conversationId: convRef.current })
				.then(({ key, publicUrl, media_type }) =>
					setPendingImages((curr) =>
						curr.map((p) =>
							p.id === id
								? {
										...p,
										url: publicUrl,
										key,
										mediaType: media_type || p.mediaType,
										status: "ready",
									}
								: p,
						),
					),
				)
				.catch(() => {
					pvMessage.error("Image upload failed");
					removePendingImage(id);
				});
		},
		[visionEnabled, removePendingImage],
	);

	const onPaste = useCallback(
		(e) => {
			const items = e.clipboardData?.items || [];
			let handled = false;
			for (const it of items) {
				if (it.kind === "file" && it.type.startsWith("image/")) {
					const f = it.getAsFile();
					if (f) {
						addImageFile(f);
						handled = true;
					}
				}
			}
			if (handled) e.preventDefault();
		},
		[addImageFile],
	);

	const onDrop = useCallback(
		(e) => {
			const files = e.dataTransfer?.files;
			if (!files?.length) return;
			let handled = false;
			for (const f of files) {
				if (f.type.startsWith("image/")) {
					addImageFile(f);
					handled = true;
				}
			}
			if (handled) e.preventDefault();
		},
		[addImageFile],
	);

	// ── Stop / recover ─────────────────────────────────────────────────────────
	const stopStreaming = useCallback(() => {
		abortRef.current?.abort();
		abortRef.current = null;
		setIsStreaming(false);
		if (convRef.current) stopConversation(convRef.current).catch(() => {});
	}, []);

	const recoverTurn = useCallback(async (convId) => {
		for (let i = 0; i < 24; i++) {
			await new Promise((r) => setTimeout(r, 2500));
			if (convRef.current !== convId) return;
			try {
				const d = await fetchConversation(convId);
				if (convRef.current !== convId) return;
				const msgs = d.messages || [];
				const last = msgs[msgs.length - 1];
				if (last && last.role === "assistant") {
					setMessages(
						msgs.map((m) => ({
							id: m.id,
							role: m.role,
							content: blocksToText(m.content),
							parts: blocksToParts(m.content),
							images: blocksToImages(m.content),
							model: m.model_used || null,
						})),
					);
					return;
				}
			} catch {
				/* keep trying */
			}
		}
	}, []);

	// Stream callbacks for a turn (shared by send + regenerate). All writes target
	// the trailing assistant message (the empty bubble we just pushed). onDone
	// stamps the model that produced the reply for the message-actions row.
	const buildHandlers = useCallback(
		(convId) => {
			const appendText = (delta) =>
				setMessages((curr) => {
					const updated = [...curr];
					const last = updated[updated.length - 1];
					updated[updated.length - 1] = {
						...last,
						parts: appendTextPart(last.parts, delta),
					};
					return updated;
				});
			return {
				onText: appendText,
				onThinking: () => {},
				onTool: (t) => {
					if (t.name === "navigate") {
						if (t.done) return;
						setMessages((curr) => {
							const updated = [...curr];
							const last = { ...updated[updated.length - 1] };
							const parts = [...(last.parts || [])];
							const a = t.args || {};
							parts.push({
								kind: "nav",
								id: `p${parts.length}`,
								target: a.target,
								navId: a.id,
								route: a.route,
								url: a.url,
								label: a.label,
							});
							last.parts = parts;
							updated[updated.length - 1] = last;
							return updated;
						});
						return;
					}
					setMessages((curr) => {
						const updated = [...curr];
						const last = { ...updated[updated.length - 1] };
						const parts = [...(last.parts || [])];
						if (t.done) {
							for (let i = parts.length - 1; i >= 0; i--) {
								if (parts[i].kind !== "tools") continue;
								const idx = parts[i].tools.findIndex((x) => x.id === t.id);
								if (idx >= 0) {
									const tools = [...parts[i].tools];
									tools[idx] = {
										...tools[idx],
										label: t.label || tools[idx].label,
										status: t.ok ? "done" : "error",
									};
									parts[i] = { ...parts[i], tools };
									break;
								}
							}
						} else {
							let run = parts[parts.length - 1];
							if (run?.kind !== "tools") {
								run = { kind: "tools", id: `p${parts.length}`, tools: [] };
								parts.push(run);
							} else {
								run = { ...run, tools: [...run.tools] };
								parts[parts.length - 1] = run;
							}
							run.tools.push({
								id: t.id,
								name: t.name,
								args: t.args,
								status: "running",
							});
						}
						last.parts = parts;
						updated[updated.length - 1] = last;
						return updated;
					});
				},
				onError: (e) => {
					if (e?.isTransport && convId) {
						appendText("\n\n_(reconnecting…)_");
						recoverTurn(convId);
						return;
					}
					appendText(`\n\n**Error:** ${e.message}`);
				},
				onDone: () => {
					// Stamp the model that produced this reply (wire id → label later).
					const used = activeModelRef.current?.model_id || null;
					if (used)
						setMessages((curr) => {
							const updated = [...curr];
							const last = updated[updated.length - 1];
							if (last?.role === "assistant")
								updated[updated.length - 1] = { ...last, model: used };
							return updated;
						});
					setIsStreaming(false);
				},
			};
		},
		[recoverTurn],
	);

	// ── Send ─────────────────────────────────────────────────────────────────
	const sendMessage = useCallback(async () => {
		const text = input.trim();
		const readyImages = pendingImages.filter(
			(p) => p.status === "ready" && p.url,
		);
		if (!text && !readyImages.length) return;
		if (sending) return;

		// Mid-stream: a send INJECTS into the running turn instead of starting one.
		if (isStreaming) {
			if (!conversationId) return;
			setMessages((curr) => {
				const next = [...curr];
				const last = next[next.length - 1];
				if (last?.role === "assistant") {
					const parts = [...(last.parts || [])];
					parts.push({ kind: "inject", id: `p${parts.length}`, text });
					next[next.length - 1] = { ...last, parts };
				}
				return next;
			});
			setInput("");
			scrollToBottom();
			try {
				await injectMessage(conversationId, text);
			} catch {
				/* 409 = the turn just ended; best-effort */
			}
			return;
		}

		const userMsg = {
			id: newMessageId(),
			role: "user",
			content: text,
			...(readyImages.length
				? {
						images: readyImages.map((p) => ({
							url: p.url,
							mediaType: p.mediaType,
						})),
					}
				: {}),
		};
		const assistantMsg = { id: newMessageId(), role: "assistant", parts: [] };
		setMessages((curr) => [...curr, userMsg, assistantMsg]);
		setInput("");
		setPendingImages((curr) => {
			for (const p of curr) if (p.localUrl) URL.revokeObjectURL(p.localUrl);
			return [];
		});
		setSending(true);
		scrollToBottom();

		let convId = conversationId;
		let created = false;
		if (!convId) {
			try {
				const conv = await createConversation({ agent: effectiveAgent });
				convId = conv.id;
				created = true;
				setModelId(conv.model_id || null);
			} catch {
				setMessages((curr) => {
					const updated = [...curr];
					const last = updated[updated.length - 1];
					updated[updated.length - 1] = {
						...last,
						parts: appendTextPart(
							last.parts,
							"**Error:** failed to start conversation",
						),
					};
					return updated;
				});
				setSending(false);
				return;
			}
		}

		setIsStreaming(true);
		setSending(false);
		// Adopt the new conversation id (page highlights it + refreshes the list).
		if (created) {
			convRef.current = convId;
			onConversationCreated?.(convId);
		}
		scrollToBottom();

		const controller = new AbortController();
		abortRef.current = controller;

		try {
			await streamChat({
				conversationId: convId,
				message: text,
				contextNoteIds: [],
				images: readyImages.map((p) => ({
					url: p.url,
					key: p.key,
					media_type: p.mediaType,
				})),
				signal: controller.signal,
				...buildHandlers(convId),
			});
		} finally {
			setIsStreaming(false);
			setSending(false);
			abortRef.current = null;
			// First turn usually mints a title server-side — refresh the rail.
			if (created) onConversationsChanged?.();
		}
	}, [
		input,
		isStreaming,
		sending,
		conversationId,
		effectiveAgent,
		pendingImages,
		buildHandlers,
		scrollToBottom,
		onConversationCreated,
		onConversationsChanged,
	]);

	// "Try again": re-run the last user turn. The last message must be an
	// assistant reply preceded by a user message; we reset that bubble to empty
	// and stream a regenerate turn (the backend drops the old assistant message).
	const regenerateLast = useCallback(async () => {
		if (isStreaming || sending) return;
		const convId = conversationId;
		if (!convId) return;
		const n = messages.length;
		const last = messages[n - 1];
		const prev = messages[n - 2];
		if (!last || last.role !== "assistant" || !prev || prev.role !== "user")
			return;
		const userText = prev.content || "";
		if (!userText) return;
		// Reset the assistant bubble in place so it re-streams into the same slot.
		setMessages((curr) => {
			const updated = [...curr];
			updated[updated.length - 1] = {
				...updated[updated.length - 1],
				parts: [],
				model: null,
			};
			return updated;
		});
		setIsStreaming(true);
		scrollToBottom();
		const controller = new AbortController();
		abortRef.current = controller;
		try {
			await streamChat({
				conversationId: convId,
				message: userText,
				contextNoteIds: [],
				images: [],
				regenerate: true,
				signal: controller.signal,
				...buildHandlers(convId),
			});
		} finally {
			setIsStreaming(false);
			abortRef.current = null;
			onConversationsChanged?.();
		}
	}, [
		isStreaming,
		sending,
		conversationId,
		messages,
		buildHandlers,
		scrollToBottom,
		onConversationsChanged,
	]);

	const pickModel = useCallback(
		async (m) => {
			setModelMenuOpen(false);
			focusInput();
			setModelId(m.id);
			if (!m.supports_vision) {
				setPendingImages((curr) => {
					if (curr.length) {
						for (const p of curr)
							if (p.localUrl) URL.revokeObjectURL(p.localUrl);
						pvMessage.info(
							`${m.display_name} can't read images — removed the attached image(s).`,
						);
					}
					return [];
				});
			}
			pvMessage.success(`Model switched to ${m.display_name}`);
			if (conversationId) {
				try {
					await updateConversation({ id: conversationId, model_id: m.id });
				} catch {
					pvMessage.error("Couldn't save the model change");
				}
			}
		},
		[conversationId, focusInput],
	);

	// ── Slash commands ─────────────────────────────────────────────────────────
	// Client commands + the active agent's prompt macros, filtered by the typed
	// token (active only while the input is a single `/word`).
	const agentCommands = useMemo(
		() => agents.find((a) => a.kind === effectiveAgent)?.commands || [],
		[agents, effectiveAgent],
	);
	const slashMatches = useMemo(() => {
		if (!input.startsWith("/") || /\s/.test(input)) return [];
		const q = input.slice(1).toLowerCase();
		const client = CLIENT_COMMANDS.map((c) => ({ ...c, kind: "client" }));
		const agent = (Array.isArray(agentCommands) ? agentCommands : []).map(
			(c) => ({ ...c, kind: "agent" }),
		);
		return [...client, ...agent].filter((c) =>
			(c.name || "").toLowerCase().startsWith(q),
		);
	}, [input, agentCommands]);

	// Wipe the current conversation's messages but keep the same conversation id
	// so the thread continues in place. With no active conversation it's a reset.
	const clearMessages = useCallback(async () => {
		abortRef.current?.abort();
		abortRef.current = null;
		setIsStreaming(false);
		setMessages([]);
		setInput("");
		setTitleMenu(false);
		if (!conversationId) return;
		try {
			await clearConversation(conversationId);
		} catch {
			/* ignore */
		}
	}, [conversationId]);

	// Resolve a /title choice: auto-rename via the LLM, or a manual prompt.
	const runTitleAction = useCallback(
		async (key) => {
			setTitleMenu(false);
			focusInput();
			if (!conversationId) return;
			if (key === "auto") {
				try {
					const r = await retitleConversation(conversationId);
					if (r?.title) setTitle(r.title);
					onConversationsChanged?.();
				} catch {
					/* ignore */
				}
				return;
			}
			const t =
				typeof window !== "undefined"
					? window.prompt("Rename conversation")
					: null;
			if (t?.trim()) {
				try {
					await updateConversation({ id: conversationId, title: t.trim() });
					setTitle(t.trim());
					onConversationsChanged?.();
				} catch {
					/* ignore */
				}
			}
		},
		[conversationId, focusInput, onConversationsChanged],
	);

	const runCommand = useCallback(
		(cmd) => {
			if (cmd.kind === "agent") {
				setInput(cmd.prompt || "");
				focusInput();
				return;
			}
			setInput("");
			if (cmd.name === "new") {
				onNewChat?.();
				return focusInput();
			}
			if (cmd.name === "clear") {
				clearMessages();
				return focusInput();
			}
			if (cmd.name === "sessions") {
				onToggleSidebar?.();
				return focusInput();
			}
			if (cmd.name === "models") {
				setModelMenuOpen(true);
				return;
			}
			if (cmd.name === "title") {
				if (!conversationId) return focusInput();
				setTitleActive(0);
				setTitleMenu(true);
			}
		},
		[conversationId, clearMessages, focusInput, onNewChat, onToggleSidebar],
	);

	const onKeyDown = (e) => {
		// /title submenu: arrows move the highlight, Enter picks, Escape dismisses.
		if (titleMenu) {
			const n = TITLE_ACTIONS.length;
			if (e.key === "ArrowDown") {
				e.preventDefault();
				setTitleActive((i) => (i + 1) % n);
				return;
			}
			if (e.key === "ArrowUp") {
				e.preventDefault();
				setTitleActive((i) => (i - 1 + n) % n);
				return;
			}
			if (e.key === "Escape") {
				e.preventDefault();
				setTitleMenu(false);
				focusInput();
				return;
			}
			if (e.key === "Enter") {
				e.preventDefault();
				runTitleAction(TITLE_ACTIONS[Math.min(titleActive, n - 1)].key);
				return;
			}
		}
		// Slash menu: arrows move the highlight, Enter/Tab run it, Escape dismisses.
		if (slashMatches.length > 0) {
			const n = slashMatches.length;
			if (e.key === "ArrowDown") {
				e.preventDefault();
				setSlashActive((i) => (i + 1) % n);
				return;
			}
			if (e.key === "ArrowUp") {
				e.preventDefault();
				setSlashActive((i) => (i - 1 + n) % n);
				return;
			}
			if (e.key === "Escape") {
				e.preventDefault();
				setInput("");
				focusInput();
				return;
			}
			if (e.key === "Enter" || e.key === "Tab") {
				e.preventDefault();
				runCommand(slashMatches[Math.min(slashActive, n - 1)]);
				return;
			}
		}
		if (e.key === "Enter" && !e.shiftKey) {
			e.preventDefault();
			sendMessage();
		}
	};

	const hasText = input.trim().length > 0;
	const hasReadyImage = pendingImages.some((p) => p.status === "ready");
	const showStop = isStreaming && !hasText;
	const canSend = (hasText || hasReadyImage) && !uploadingImages;

	return (
		<section className="chatx-conv">
			<header className="chatx-conv-head">
				<button
					type="button"
					className="chatx-hamburger"
					onClick={onToggleSidebar}
					aria-label="Toggle conversations"
					title="Conversations"
				>
					☰
				</button>
				<div className="chatx-conv-titlewrap">
					<span className="chatx-conv-title">
						{title || (conversationId ? "Untitled" : "New chat")}
					</span>
					{meta?.created_at ? (
						<span className="chatx-conv-meta">
							{(() => {
								const c = formatDateTime(meta.created_at);
								return `created ${c.date} ${c.time}`;
							})()}
							{meta.updated_at && meta.updated_at !== meta.created_at
								? ` · edited ${timeAgo(meta.updated_at)}`
								: ""}
						</span>
					) : null}
				</div>
				<div className={`chatx-status${isStreaming ? " streaming" : ""}`}>
					<span className="chatx-status-dot" />
				</div>
				<div className="chatx-model">
					<button
						type="button"
						className="chatx-model-btn"
						onClick={() => setModelMenuOpen((o) => !o)}
						title="Model for this chat"
					>
						<span className="chatx-model-name">
							{activeModel?.display_name || "default model"}
						</span>
						<DownOutlined className="chatx-model-caret" />
					</button>
					{modelMenuOpen ? (
						<>
							<button
								type="button"
								className="chatx-model-backdrop"
								aria-label="Close model menu"
								onClick={() => setModelMenuOpen(false)}
							/>
							<div className="chatx-model-menu">
								{allModels.length === 0 ? (
									<div className="picker-empty">None</div>
								) : (
									allModels.map((m) => {
										const inUse = modelId ? m.id === modelId : m.is_default;
										return (
											<button
												key={m.id}
												type="button"
												className={`picker-item${inUse ? " is-current" : ""}`}
												onClick={() => pickModel(m)}
											>
												{/* Left mark: the in-use model shows the accent (selected)
												    diamond; otherwise the default model shows a white one.
												    When the default IS selected, the selected diamond
												    takes the slot. */}
												<span
													className={`picker-item-mark${!inUse && m.is_default ? " chatx-mark-default" : ""}`}
													title={
														inUse
															? "Selected model"
															: m.is_default
																? "Default model"
																: undefined
													}
													aria-hidden="true"
												>
													{inUse || m.is_default ? "◆" : ""}
												</span>
												{m.display_name}{" "}
												<span className="picker-item-meta">{m.provider}</span>
											</button>
										);
									})
								)}
							</div>
						</>
					) : null}
				</div>
			</header>

			<div className="chat-messages-viewport">
				<div ref={scrollRef} className="chat-messages" onScroll={handleScroll}>
					<div className="chat-messages-inner">
						{loadingConv && messages.length === 0 ? (
							<div className="chat-loading">
								<SpriteRunner pixelSize={3} />
								<span className="chat-loading-label">
									loading conversation…
								</span>
							</div>
						) : messages.length === 0 ? (
							<div className="chat-empty">
								<div className="chat-empty-title">{agentLabel} is ready.</div>
								<div className="chat-empty-sub">
									Ask anything — markdown, code, plans. Streams back token by
									token.
								</div>
							</div>
						) : (
							messages.map((m, i) => {
								const isLast = i === messages.length - 1;
								const streamingThis =
									isStreaming && isLast && m.role === "assistant";
								return m.role === "user" ? (
									<UserBubble
										key={m.id}
										content={m.content}
										images={m.images}
									/>
								) : (
									<div key={m.id} className="chatx-msg">
										<AssistantBubble
											parts={m.parts}
											isStreaming={streamingThis}
											label={agentLabel}
											onNavigate={goTo}
										/>
										{!streamingThis && m.parts?.length ? (
											<MessageActions
												text={partsToText(m.parts)}
												modelLabel={modelLabelFor(m)}
												canRetry={isLast && !isStreaming && !sending}
												onRetry={regenerateLast}
											/>
										) : null}
									</div>
								);
							})
						)}
					</div>
				</div>
				{showJump ? (
					<button
						type="button"
						className="chat-jump"
						onClick={scrollToBottom}
						title="Jump to latest"
						aria-label="Jump to latest message"
					>
						↓
					</button>
				) : null}
			</div>

			<div className="chat-composer">
				<div className="chat-composer-inner">
					{pendingImages.length > 0 ? (
						<div className="chat-image-tags">
							{pendingImages.map((img) => (
								<div
									key={img.id}
									className={`chat-image-tag${img.status === "uploading" ? " is-uploading" : ""}${img.status === "error" ? " is-error" : ""}`}
									title={img.name}
								>
									<img
										className="chat-image-tag-thumb"
										src={img.localUrl || img.url}
										alt={img.name}
									/>
									<span className="chat-image-tag-meta">
										<span className="chat-image-tag-name">{img.name}</span>
										{img.w && img.h ? (
											<span className="chat-image-tag-dim">
												{img.w}×{img.h}
											</span>
										) : null}
									</span>
									{img.status === "uploading" ? (
										<span className="chat-image-tag-spin" aria-hidden="true" />
									) : (
										<button
											type="button"
											className="chat-image-tag-remove"
											onClick={() => removePendingImage(img.id)}
											aria-label={`Remove ${img.name}`}
										>
											×
										</button>
									)}
								</div>
							))}
						</div>
					) : null}
					<div className="chat-composer-fields">
						{slashMatches.length > 0 ? (
							<div className="slash-menu">
								{slashMatches.map((c, i) => (
									<button
										key={`${c.kind}-${c.name}`}
										type="button"
										className={`slash-item${i === slashActive ? " is-active" : ""}${c.kind === "agent" ? " slash-item--agent" : ""}`}
										onClick={() => runCommand(c)}
										onMouseEnter={() => setSlashActive(i)}
									>
										<span className="slash-item-name">/{c.name}</span>
										<span className="slash-item-desc">
											{c.description}
											{c.kind === "agent" ? " · agent" : ""}
										</span>
									</button>
								))}
							</div>
						) : null}
						{titleMenu ? (
							<div className="slash-menu">
								{TITLE_ACTIONS.map((a, i) => (
									<button
										key={a.key}
										type="button"
										className={`slash-item${i === titleActive ? " is-active" : ""}`}
										onClick={() => runTitleAction(a.key)}
										onMouseEnter={() => setTitleActive(i)}
									>
										<span className="slash-item-name">{a.label}</span>
										<span className="slash-item-desc">{a.desc}</span>
									</button>
								))}
							</div>
						) : null}
						{/* biome-ignore lint/a11y/noStaticElementInteractions: drop zone for image attachments */}
						<div
							className="chat-composer-row"
							onDrop={onDrop}
							onDragOver={(e) => {
								if (visionEnabled) e.preventDefault();
							}}
						>
							<button
								type="button"
								className="chatx-attach"
								onClick={() => fileRef.current?.click()}
								disabled={!visionEnabled}
								title={
									visionEnabled
										? "Attach an image"
										: "This model can't read images"
								}
							>
								＋
							</button>
							<input
								ref={fileRef}
								type="file"
								accept="image/*"
								multiple
								hidden
								onChange={(e) => {
									for (const f of e.target.files || []) addImageFile(f);
									e.target.value = "";
								}}
							/>
							<textarea
								ref={inputRef}
								className="chat-input"
								value={input}
								onChange={(e) => {
									setInput(e.target.value);
									setSlashActive(0);
									setTitleMenu(false);
								}}
								onKeyDown={onKeyDown}
								onPaste={onPaste}
								placeholder={`Ask ${agentLabel} anything…`}
								rows={1}
							/>
							{sending ? (
								<button
									type="button"
									className="chat-send"
									disabled
									title="Sending…"
								>
									<span className="chat-send-spinner" /> send
								</button>
							) : showStop ? (
								<button
									type="button"
									className="chat-send chat-stop"
									onClick={stopStreaming}
									title="Stop the agent"
								>
									stop ◼
								</button>
							) : (
								<button
									type="button"
									className="chat-send"
									onClick={sendMessage}
									disabled={!canSend}
								>
									send ↑
								</button>
							)}
						</div>
					</div>
				</div>
			</div>
		</section>
	);
}
