import {
	CheckCircleOutlined,
	CloseCircleOutlined,
	CommentOutlined,
	DeleteOutlined,
	ExperimentOutlined,
	ReadOutlined,
	ReloadOutlined,
	RobotOutlined,
	ThunderboltOutlined,
} from "@ant-design/icons";
import {
	Empty,
	Input,
	Segmented,
	Select,
	Spin,
	Table,
	Tabs,
	Tooltip,
} from "antd";
import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import {
	useConfirmMemoryEntry,
	useDeleteMemoryEntry,
	useEntryStats,
	useMemoryEntries,
	useMemoryOverview,
	useRejectMemoryEntry,
	useSearchConversations,
	useTurnLogs,
} from "../../../queries";
import { formatDateTime, timeAgo } from "../../../utils/dateTime";
import { PageContent } from "../../components/layout/PageLayout";
import {
	PvButton,
	PvExpander,
	PvPopconfirm,
	pvMessage,
} from "../../components/ui";
import "../../vault-pixel.css";
import "./memory.css";

const AGENT = "vault_agent";

// status / source → pixel tag tone (see .mem-tag--* in memory.css).
const STATUS_TONE = { confirmed: "green", pending: "gold", rejected: "" };
const SOURCE_TONE = {
	user_stated: "blue",
	agent_observed: "green",
	dialectic_derived: "purple",
	imported: "blue",
};
const SOURCE_LABEL = {
	user_stated: "user-stated",
	agent_observed: "observed",
	dialectic_derived: "derived",
	imported: "imported",
};

const MemTag = ({ tone, children }) => (
	<span className={tone ? `mem-tag mem-tag--${tone}` : "mem-tag"}>
		{children}
	</span>
);
const StatusTag = ({ status }) => (
	<MemTag tone={STATUS_TONE[status]}>{status}</MemTag>
);
const SourceTag = ({ source }) => (
	<MemTag tone={SOURCE_TONE[source]}>{SOURCE_LABEL[source] || source}</MemTag>
);

// L3 search snippets arrive with matched terms wrapped in « » — highlight them.
// Split keeps capture groups (odd indices = matched), keyed by char offset so
// there's no array-index key.
const Snippet = ({ text }) => {
	if (!text) return <span className="mem-muted">—</span>;
	const parts = text.split(/«([^»]*)»/g);
	let offset = 0;
	const segs = [];
	for (let i = 0; i < parts.length; i++) {
		const part = parts[i];
		if (part) segs.push({ key: offset, part, hl: i % 2 === 1 });
		offset += part.length;
	}
	return (
		<span className="mem-snippet">
			{segs.map((s) =>
				s.hl ? (
					<mark key={s.key} className="mem-hl">
						{s.part}
					</mark>
				) : (
					<span key={s.key}>{s.part}</span>
				),
			)}
		</span>
	);
};

// Pixel capacity bar (replaces antd Progress).
const Bar = ({ pct }) => {
	const p = Math.max(0, Math.min(pct ?? 0, 100));
	const tone =
		p >= 80 ? " mem-bar-fill--hot" : p >= 50 ? " mem-bar-fill--warn" : "";
	return (
		<div className="mem-bar">
			<div className={`mem-bar-fill${tone}`} style={{ width: `${p}%` }} />
		</div>
	);
};

/** A clickable layer summary card. */
const LayerCard = ({
	icon,
	layer,
	title,
	subtitle,
	count,
	accent,
	onClick,
	active,
}) => (
	<button
		type="button"
		className={`mem-layer ${active ? "mem-layer--active" : ""}`}
		style={{ "--mem-accent": accent }}
		onClick={onClick}
	>
		<div className="mem-layer-head">
			<span className="mem-layer-icon">{icon}</span>
			<span className="mem-layer-tag">{layer}</span>
		</div>
		<div className="mem-layer-count">{count}</div>
		<div className="mem-layer-title">{title}</div>
		<div className="mem-layer-sub">{subtitle}</div>
	</button>
);

const LEGEND_STATUS = [
	[
		"confirmed",
		"green",
		"Trusted fact. Injected into the agent's context whenever it's relevant (normal relevance floor).",
	],
	[
		"pending",
		"gold",
		"Low-trust. Auto-derived by the background dialectic pass and awaiting your confirmation. Injected only when VERY strongly relevant (tighter floor), and auto-expires after 60 days if never confirmed.",
	],
	[
		"rejected",
		"",
		"Discarded — kept for the record but never retrieved or injected.",
	],
];
const LEGEND_SOURCE = [
	["user-stated", "blue", "The user said it directly — highest trust."],
	[
		"observed",
		"green",
		"The agent saved it from a conversation (via the memory_save tool).",
	],
	[
		"derived",
		"purple",
		"Auto-generated by L2's dialectic pass from recent turns. Always starts as pending.",
	],
	["imported", "blue", "Bulk-loaded from another source."],
];

/** Collapsible legend explaining statuses, sources, categories, and layers. */
const Legend = () => (
	<details className="mem-legend">
		<summary>What do these mean? — statuses, sources &amp; categories</summary>
		<div className="mem-legend-grid">
			<div>
				<h4>Status — trust &amp; retrieval</h4>
				{LEGEND_STATUS.map(([label, tone, desc]) => (
					<div key={label} className="mem-legend-row">
						<MemTag tone={tone}>{label}</MemTag>
						<span>{desc}</span>
					</div>
				))}
			</div>
			<div>
				<h4>Source — where it came from</h4>
				{LEGEND_SOURCE.map(([label, tone, desc]) => (
					<div key={label} className="mem-legend-row">
						<MemTag tone={tone}>{label}</MemTag>
						<span>{desc}</span>
					</div>
				))}
			</div>
			<div>
				<h4>Category — topical label</h4>
				<p className="mem-legend-note">
					Free-form labels the agent assigns to group/filter facts (e.g.
					preferences, personal, work, health, convention, pattern, goal,
					constraint). Not a fixed list — the agent picks them.
				</p>
				<h4 style={{ marginTop: 14 }}>Layers</h4>
				<p className="mem-legend-note">
					<b>L1</b> always-in-context scratchpad (always in the prompt) ·{" "}
					<b>L2</b> semantic facts retrieved by relevance — confirmed ones plus
					low-trust <b>pending</b> guesses from L2's dialectic pass, awaiting
					confirmation · <b>L3</b> full-text search over chat history
					(on-demand).
				</p>
			</div>
		</div>
	</details>
);

/** Collapsible explainer for the per-row corroboration metrics (the expander). */
const MetricsLegend = () => (
	<details className="mem-legend">
		<summary>How corroboration works — the metrics inside each row</summary>
		<div className="mem-legend-grid">
			<div>
				<h4>Nearest entry &amp; distance</h4>
				<p className="mem-legend-note">
					Expanding a row shows its closest other memory <i>by meaning</i> and
					the <b>cosine distance</b> between them — <b>0 = identical</b>, higher
					= less alike (also shown as a similarity %). This is the
					"corroboration value": how close this fact is to one the agent already
					holds.
				</p>
			</div>
			<div>
				<h4>Merge threshold &amp; the track</h4>
				<p className="mem-legend-note">
					The number line runs <b>0 → 0.7</b>. The shaded green zone is the{" "}
					<b>merge threshold</b> (currently <b>0.40</b>): if the nearest entry
					(the ◆ pin) lands inside it, the pair is close enough to be checked as
					the same fact. Outside it, they're treated as distinct and no check
					runs.
				</p>
			</div>
			<div>
				<h4>NLI verdict</h4>
				<p className="mem-legend-note">
					For in-band pairs a model judges the relationship:{" "}
					<MemTag tone="green">entails</MemTag> = same fact (→ corroborate /
					merge), <MemTag tone="gold">contradicts</MemTag> = they conflict
					(newer supersedes the older), <MemTag tone="blue">neutral</MemTag> =
					different facts on the same topic (both kept). Distance alone can't
					tell a reword from a sibling fact — NLI makes the call.
				</p>
			</div>
			<div>
				<h4>Would promote on re-derive</h4>
				<p className="mem-legend-note">
					Whether a fresh dialectic re-derivation of this fact would
					auto-promote it from <b>pending → confirmed</b> (nearest is in-band{" "}
					<i>and</i> NLI says <code>entails</code>). This is how a guessed fact
					graduates to a trusted one without you clicking ✓.
				</p>
			</div>
		</div>
	</details>
);

/** One-line explainer shown at the top of each tab. */
const TabIntro = ({ children }) => <p className="mem-intro">{children}</p>;

// Render any raw field value into something readable in the detail expander.
const formatValue = (key, value) => {
	if (value == null || value === "")
		return <span className="mem-muted">—</span>;
	if (typeof value === "boolean")
		return <MemTag tone={value ? "green" : ""}>{String(value)}</MemTag>;
	if (Array.isArray(value))
		return value.length ? (
			value.map((v) => <MemTag key={String(v)}>{String(v)}</MemTag>)
		) : (
			<span className="mem-muted">empty</span>
		);
	// Timestamp columns → friendly local datetime (+ relative).
	if (/_at$/.test(key)) {
		const dt = formatDateTime(value);
		return (
			<span>
				{dt?.date} {dt?.time}{" "}
				<span className="mem-muted">({timeAgo(value)})</span>
			</span>
		);
	}
	return <span>{String(value)}</span>;
};

const pct1 = (n) => `${(n ?? 0).toFixed(1)}%`;
const dist3 = (n) => (n ?? 0).toFixed(3);

const NLI_TONE = { entails: "green", contradicts: "gold", neutral: "blue" };

// Marks on the 0 → 0.7 cosine-distance track for the corroboration visual.
const TRACK_MAX = 0.7;
const trackPos = (d) => `${Math.min(100, Math.max(0, (d / TRACK_MAX) * 100))}%`;

/**
 * Corroboration metrics for one entry: how close its nearest neighbour is, and
 * whether that's inside the merge threshold (and the NLI verdict if so) — i.e.
 * how close a re-derivation of this fact is to being auto-promoted.
 */
const CorroborationStats = ({ id }) => {
	const { data, isLoading } = useEntryStats(id);
	if (isLoading) return <Spin size="small" />;
	if (!data) return <span className="mem-muted">No metrics available.</span>;

	const t = data.thresholds || {};
	const n = data.nearest;
	if (!n) {
		return (
			<div className="mem-stats">
				<span className="mem-muted">
					{data.note || "No nearest neighbour."}
				</span>
			</div>
		);
	}

	const inBand = data.within_corroborate_band;
	const headroom = data.headroom_pct ?? 0;

	return (
		<div className="mem-stats">
			{/*
			 * Distance number line: 0 (identical) → TRACK_MAX (unrelated). The
			 * shaded zone (0 → merge threshold) is "close enough to be the same
			 * fact"; the ◆ marks where the nearest other memory actually sits.
			 */}
			<div className="mem-track">
				<div
					className="mem-track-zone"
					style={{ width: trackPos(t.corroborate_distance) }}
				/>
				<div
					className="mem-track-tick"
					style={{ left: trackPos(t.corroborate_distance) }}
				/>
				<div
					className={`mem-track-pin ${inBand ? "mem-track-pin--in" : ""}`}
					style={{ left: trackPos(n.distance) }}
				>
					<span className="mem-track-pin-label">{dist3(n.distance)}</span>
				</div>
			</div>
			<div className="mem-track-axis">
				<span>0 · identical</span>
				<span className="mem-track-axis-corr">
					merge ≤ {dist3(t.corroborate_distance)}
				</span>
				<span>{TRACK_MAX} · unrelated</span>
			</div>
			<p className="mem-track-caption">
				Nearest memory is at <b>{dist3(n.distance)}</b> (
				{pct1(n.similarity_pct)} similar).{" "}
				{inBand ? (
					<>
						Inside the merge zone — NLI was asked if it's the same fact and said{" "}
						<b>{data.nli || "…"}</b>.
					</>
				) : (
					<>
						<b>{pct1(-headroom)}</b> beyond the merge threshold, so it's treated
						as a distinct fact (NLI not run).
					</>
				)}
			</p>

			<div className="mem-kv">
				<div className="mem-kv-row">
					<span className="mem-kv-key">nearest entry</span>
					<span className="mem-kv-val">
						<SourceTag source={n.source} />
						<StatusTag status={n.status} />
						<span>{n.content}</span>
					</span>
				</div>
				<div className="mem-kv-row">
					<span className="mem-kv-key">distance</span>
					<span className="mem-kv-val">
						<b>{dist3(n.distance)}</b>
						<span className="mem-muted">
							cosine · {pct1(n.similarity_pct)} similar
						</span>
					</span>
				</div>
				<div className="mem-kv-row">
					<span className="mem-kv-key">corroborate band</span>
					<span className="mem-kv-val">
						<MemTag tone={inBand ? "green" : ""}>
							{inBand ? "inside" : "outside"} (≤ {dist3(t.corroborate_distance)}
							)
						</MemTag>
						<span className="mem-muted">
							{headroom >= 0
								? `${pct1(headroom)} headroom`
								: `${pct1(-headroom)} beyond threshold`}
						</span>
					</span>
				</div>
				<div className="mem-kv-row">
					<span className="mem-kv-key">NLI verdict</span>
					<span className="mem-kv-val">
						{data.nli ? (
							<MemTag tone={NLI_TONE[data.nli] || ""}>{data.nli}</MemTag>
						) : (
							<span className="mem-muted">n/a (outside band — not run)</span>
						)}
					</span>
				</div>
				<div className="mem-kv-row">
					<span className="mem-kv-key">would promote on re-derive</span>
					<span className="mem-kv-val">
						<MemTag tone={data.would_corroborate_on_rederive ? "green" : ""}>
							{data.would_corroborate_on_rederive ? "yes" : "no"}
						</MemTag>
					</span>
				</div>
			</div>
		</div>
	);
};

/**
 * Expander body for an entry row: the corroboration metrics on top, then a
 * key/value grid of every raw field the API returns for that memory line.
 */
const EntryDetail = ({ row }) => (
	<div className="mem-detail">
		<div className="mem-detail-sec">
			<h4 className="mem-detail-head">Corroboration metrics</h4>
			<CorroborationStats id={row.id} />
		</div>
		<div className="mem-detail-sec">
			<h4 className="mem-detail-head">All fields</h4>
			<div className="mem-kv">
				{Object.entries(row).map(([key, value]) => (
					<div key={key} className="mem-kv-row">
						<span className="mem-kv-key">{key}</span>
						<span className="mem-kv-val">{formatValue(key, value)}</span>
					</div>
				))}
			</div>
		</div>
	</div>
);

/** L1 capacity gauge. */
const L1Gauge = ({ label, chars, cap, pct, content }) => (
	<div className="mem-gauge">
		<div className="mem-gauge-head">
			<span className="mem-gauge-label">{label}</span>
			<span className="mem-gauge-num">
				{chars} / {cap} chars · {pct}%
			</span>
		</div>
		<Bar pct={pct} />
		<pre className="mem-gauge-body">
			{content?.trim() ? content : <span className="mem-muted">— empty —</span>}
		</pre>
	</div>
);

const Memory = () => {
	const [tab, setTab] = useState("entries");
	const [status, setStatus] = useState("all");
	const [source, setSource] = useState();
	const [category, setCategory] = useState();
	const [search, setSearch] = useState("");
	const [convQuery, setConvQuery] = useState("");

	const overview = useMemoryOverview(AGENT);
	const entryFilters = useMemo(() => {
		const f = { agent: AGENT };
		if (status !== "all") f.status = status;
		if (source) f.source = source;
		if (category) f.category = category;
		if (search.trim()) f.q = search.trim();
		return f;
	}, [status, source, category, search]);
	const entries = useMemoryEntries(entryFilters);
	const turnLogs = useTurnLogs(
		{ agent: AGENT },
		{ enabled: tab === "inspector" },
	);
	// Empty query → browse recent conversations; typed query → full-text search.
	const conversations = useSearchConversations(
		{ agent: AGENT, q: convQuery },
		{ enabled: tab === "conversations" },
	);

	const confirmMut = useConfirmMemoryEntry();
	const rejectMut = useRejectMemoryEntry();
	const deleteMut = useDeleteMemoryEntry();

	const stats = overview.data?.stats;
	const l1 = overview.data?.l1;
	// Combined L1 footprint: both `memory` and `user_context` are injected every
	// turn, so the card reflects total usage, not just the agent scratchpad.
	const l1CombinedPct = l1
		? Math.round(
				((l1.memory_chars + l1.user_context_chars) * 100) /
					(l1.memory_cap + l1.user_context_cap),
			)
		: 0;
	const l3 = overview.data?.l3;
	const byStatus = stats?.by_status || {};
	const bySource = stats?.by_source || {};

	const refreshAll = () => {
		overview.refetch();
		entries.refetch();
		if (tab === "inspector") turnLogs.refetch();
		if (tab === "conversations") conversations.refetch();
	};

	const act = (mut, id, verb) =>
		mut.mutate(id, {
			onSuccess: () => pvMessage.success(`Entry ${verb}`),
			onError: () => pvMessage.error(`Could not ${verb} entry`),
		});

	// Clicking a layer card focuses the entries tab on that slice.
	const focusLayer = (next) => {
		setTab("entries");
		setStatus(next.status ?? "all");
		setSource(next.source);
	};

	const entryColumns = [
		{
			title: "Memory line",
			dataIndex: "content",
			key: "content",
			render: (text, row) => (
				<div className="mem-cell-content">
					<span>{text}</span>
					{!row.embedded && (
						<Tooltip title="No embedding yet (queued / provider down)">
							<MemTag tone="gold">no vector</MemTag>
						</Tooltip>
					)}
				</div>
			),
		},
		{
			title: "Status",
			dataIndex: "status",
			key: "status",
			width: 110,
			render: (s) => <StatusTag status={s} />,
		},
		{
			title: "Source",
			dataIndex: "source",
			key: "source",
			width: 120,
			render: (s) => <SourceTag source={s} />,
		},
		{
			title: "Category",
			dataIndex: "category",
			key: "category",
			width: 120,
			render: (c) =>
				c ? <MemTag>{c}</MemTag> : <span className="mem-muted">—</span>,
		},
		{
			title: "Conf.",
			dataIndex: "confidence",
			key: "confidence",
			width: 80,
			render: (c) => <span className="mem-muted">{c}</span>,
		},
		{
			title: "Created",
			dataIndex: "created_at",
			key: "created_at",
			width: 120,
			render: (d) => (
				<Tooltip
					title={`${formatDateTime(d)?.date} ${formatDateTime(d)?.time}`}
				>
					<span className="mem-muted">{timeAgo(d)}</span>
				</Tooltip>
			),
		},
		{
			title: "",
			key: "actions",
			width: 120,
			render: (_, row) => (
				<div className="mem-actions">
					{row.status !== "confirmed" && (
						<Tooltip title="Confirm (promote to a trusted fact)">
							<PvButton
								size="small"
								icon={<CheckCircleOutlined />}
								onClick={() => act(confirmMut, row.id, "confirmed")}
							/>
						</Tooltip>
					)}
					{row.status !== "rejected" && (
						<Tooltip title="Reject (stop retrieving it)">
							<PvButton
								size="small"
								icon={<CloseCircleOutlined />}
								onClick={() => act(rejectMut, row.id, "rejected")}
							/>
						</Tooltip>
					)}
					<PvPopconfirm
						title="Delete this entry permanently?"
						okText="Delete"
						okVariant="danger"
						onConfirm={() => act(deleteMut, row.id, "deleted")}
					>
						<PvButton size="small" danger icon={<DeleteOutlined />} />
					</PvPopconfirm>
				</div>
			),
		},
	];

	const inspectorColumns = [
		{
			title: "When",
			dataIndex: "created_at",
			key: "created_at",
			width: 130,
			render: (d) => <span className="mem-muted">{timeAgo(d)}</span>,
		},
		{
			title: "Conversation",
			dataIndex: "title",
			key: "title",
			render: (t) => t || <span className="mem-muted">untitled</span>,
		},
		{
			title: "Retrieved",
			key: "retrieved",
			width: 110,
			render: (_, row) => (
				<MemTag tone={row.retrieved?.length ? "green" : ""}>
					{row.retrieved?.length || 0} memo
				</MemTag>
			),
		},
		{
			title: "L1 usage",
			key: "l1",
			width: 140,
			render: (_, row) =>
				row.l1_memory_pct != null ? (
					<div className="mem-cell-content">
						<Bar pct={row.l1_memory_pct} />
						<span className="mem-muted">{row.l1_memory_pct}%</span>
					</div>
				) : (
					<span className="mem-muted">—</span>
				),
		},
	];

	const convColumns = [
		{
			title: "When",
			dataIndex: "created_at",
			key: "created_at",
			width: 110,
			render: (d) => (
				<Tooltip
					title={`${formatDateTime(d)?.date} ${formatDateTime(d)?.time}`}
				>
					<span className="mem-muted">{timeAgo(d)}</span>
				</Tooltip>
			),
		},
		{
			title: "Conversation",
			dataIndex: "title",
			key: "title",
			width: 220,
			render: (t) => t || <span className="mem-muted">untitled</span>,
		},
		{
			title: convQuery.trim() ? "Hits" : "Msgs",
			dataIndex: "matches",
			key: "matches",
			width: 64,
			render: (m) => <MemTag tone="blue">{m}</MemTag>,
		},
		{
			title: "Match",
			dataIndex: "snippet",
			key: "snippet",
			render: (s) => <Snippet text={s} />,
		},
	];

	return (
		<PageContent>
			<div className="mem-root">
				<div className="vp-page-head">
					<div>
						<h1 className="vp-page-title">Memory</h1>
						<p className="vp-page-subtitle">
							Scout and curate the agent's layered memory — L1
							always-in-context, L2 semantic store (incl. dialectic-derived
							guesses), L3 conversation search.
						</p>
					</div>
					<div className="mem-header-actions">
						<Link to="/docs/agent-memory">
							<PvButton icon={<ReadOutlined />}>Docs</PvButton>
						</Link>
						<PvButton icon={<ReloadOutlined />} onClick={refreshAll}>
							Refresh
						</PvButton>
					</div>
				</div>

				{/* Layer map */}
				<div className="mem-layers">
					<LayerCard
						layer="L1"
						icon={<RobotOutlined />}
						title="Always-in-context"
						subtitle={`scratchpad ${l1?.memory_pct ?? 0}% · profile ${l1?.user_context_pct ?? 0}%`}
						count={l1 ? `${l1CombinedPct}%` : "—"}
						accent="var(--vp-accent-4)"
						active={tab === "l1"}
						onClick={() => setTab("l1")}
					/>
					<LayerCard
						layer="L2"
						icon={<CheckCircleOutlined />}
						title="Total active"
						subtitle={`${stats?.unembedded ?? 0} awaiting embedding`}
						count={stats?.total ?? 0}
						accent="var(--vp-accent)"
						active={tab === "entries" && status === "all" && !source}
						onClick={() => focusLayer({ status: "all" })}
					/>
					<LayerCard
						layer="L2"
						icon={<ThunderboltOutlined />}
						title="Confirmed facts"
						subtitle={`${bySource.user_stated || 0} user · ${bySource.agent_observed || 0} observed`}
						count={byStatus.confirmed ?? 0}
						accent="var(--vp-accent-2)"
						active={tab === "entries" && status === "confirmed"}
						onClick={() => focusLayer({ status: "confirmed" })}
					/>
					<LayerCard
						layer="L2"
						icon={<ExperimentOutlined />}
						title="Pending review"
						subtitle="low-trust L2 guesses, awaiting confirmation"
						count={byStatus.pending ?? 0}
						accent="#b07cff"
						active={tab === "entries" && status === "pending"}
						onClick={() => focusLayer({ status: "pending" })}
					/>
					<LayerCard
						layer="L3"
						icon={<CommentOutlined />}
						title="Conversation search"
						subtitle={`${l3?.conversations ?? 0} conversations indexed`}
						count={l3?.messages ?? 0}
						accent="var(--vp-accent)"
						active={tab === "conversations"}
						onClick={() => setTab("conversations")}
					/>
				</div>

				<Tabs
					activeKey={tab}
					onChange={setTab}
					items={[
						{
							key: "l1",
							label: "Always-in-context (L1)",
							children: overview.isLoading ? (
								<Spin />
							) : (
								<>
									<TabIntro>
										<b>Always-in-context.</b> These two fields are injected into{" "}
										<i>every</i> prompt, so they stay small and hard-capped.{" "}
										<b>memory</b> = the agent's own running notes (it rarely
										writes here — most facts go to L2); <b>user_context</b> =
										your profile / preferences. Bulk memory lives in the Entries
										tab.
									</TabIntro>
									<div className="mem-l1">
										<L1Gauge
											label="memory — agent scratchpad"
											chars={l1?.memory_chars ?? 0}
											cap={l1?.memory_cap ?? 0}
											pct={l1?.memory_pct ?? 0}
											content={l1?.memory}
										/>
										<L1Gauge
											label="user_context — profile / preferences"
											chars={l1?.user_context_chars ?? 0}
											cap={l1?.user_context_cap ?? 0}
											pct={l1?.user_context_pct ?? 0}
											content={l1?.user_context}
										/>
									</div>
								</>
							),
						},
						{
							key: "entries",
							label: "Entries (L2)",
							children: (
								<>
									<Legend />
									<MetricsLegend />
									<TabIntro>
										<b>Long-term semantic memory (L2).</b> Each row is one fact
										the agent can recall by relevance. <b>Confirmed</b> =
										trusted, retrieved freely; <b>pending</b> = an unconfirmed
										guess (mostly from L2's dialectic pass), retrieved only when
										strongly relevant and auto-expiring after 60 days. Use the
										row buttons to confirm, reject, or delete.
									</TabIntro>
									<div className="mem-filters">
										<Segmented
											value={status}
											onChange={setStatus}
											options={[
												{ label: "All", value: "all" },
												{ label: "Confirmed", value: "confirmed" },
												{ label: "Pending", value: "pending" },
												{ label: "Rejected", value: "rejected" },
											]}
										/>
										<Select
											allowClear
											placeholder="Source"
											popupClassName="mem-pop"
											style={{ minWidth: 150 }}
											value={source}
											onChange={setSource}
											options={[
												{ label: "User-stated", value: "user_stated" },
												{ label: "Observed", value: "agent_observed" },
												{ label: "Derived", value: "dialectic_derived" },
												{ label: "Imported", value: "imported" },
											]}
										/>
										<Select
											allowClear
											placeholder="Category"
											popupClassName="mem-pop"
											style={{ minWidth: 150 }}
											value={category}
											onChange={setCategory}
											options={(stats?.by_category || []).map((c) => ({
												label: `${c.category} (${c.count})`,
												value: c.category,
											}))}
										/>
										<Input.Search
											allowClear
											placeholder="Search content…"
											style={{ maxWidth: 240 }}
											onSearch={setSearch}
											onChange={(e) => !e.target.value && setSearch("")}
										/>
									</div>
									<Table
										className="vp-table"
										rowKey="id"
										size="small"
										loading={entries.isLoading}
										dataSource={entries.data || []}
										columns={entryColumns}
										pagination={{ pageSize: 20, hideOnSinglePage: true }}
										expandable={{
											expandedRowRender: (row) => <EntryDetail row={row} />,
											expandIcon: PvExpander,
										}}
										locale={{
											emptyText: <Empty description="No memory entries" />,
										}}
									/>
								</>
							),
						},
						{
							key: "conversations",
							label: "Conversation search (L3)",
							children: (
								<>
									<TabIntro>
										<b>Full-text search over chat history (L3).</b> The agent's{" "}
										<code>search_conversations</code> tool searches the verbatim
										transcript of past conversations — complementing L2, which
										only stores distilled facts. On-demand only; never
										auto-injected. Recent conversations are listed below; type
										to run the same full-text search the agent does.
									</TabIntro>
									<div className="mem-filters">
										<Input.Search
											allowClear
											enterButton
											placeholder="Search past conversations…"
											style={{ maxWidth: 360 }}
											onSearch={setConvQuery}
											onChange={(e) => !e.target.value && setConvQuery("")}
										/>
									</div>
									<Table
										className="vp-table"
										rowKey="conversation_id"
										size="small"
										loading={conversations.isFetching}
										dataSource={conversations.data || []}
										columns={convColumns}
										pagination={{ pageSize: 15, hideOnSinglePage: true }}
										locale={{
											emptyText: (
												<Empty
													description={
														convQuery.trim()
															? "No conversations matched"
															: "No conversations yet"
													}
												/>
											),
										}}
									/>
								</>
							),
						},
						{
							key: "inspector",
							label: "Turn inspector",
							children: (
								<>
									<TabIntro>
										<b>What the agent knew each turn.</b> One row per completed
										turn: how many L2 memories were retrieved into context
										(expand a row to see them with similarity %) and how full L1
										was. Empty until you chat with the agent — this is the
										feedback loop for tuning retrieval.
									</TabIntro>
									<Table
										className="vp-table"
										rowKey="id"
										size="small"
										loading={turnLogs.isLoading}
										dataSource={turnLogs.data || []}
										columns={inspectorColumns}
										pagination={{ pageSize: 15, hideOnSinglePage: true }}
										locale={{
											emptyText: (
												<Empty description="No turns logged yet — chat with the agent first" />
											),
										}}
										expandable={{
											expandedRowRender: (row) => (
												<div className="mem-retrieved">
													{row.retrieved?.length ? (
														row.retrieved.map((r) => (
															<div key={r.id} className="mem-retrieved-row">
																<SourceTag source={r.source} />
																<StatusTag status={r.status} />
																<span className="mem-retrieved-sim">
																	{Math.round((1 - (r.distance ?? 1)) * 100)}%
																</span>
																<span>{r.content}</span>
															</div>
														))
													) : (
														<span className="mem-muted">
															Nothing cleared the retrieval floor this turn.
														</span>
													)}
												</div>
											),
											expandIcon: PvExpander,
										}}
									/>
								</>
							),
						},
					]}
				/>
			</div>
		</PageContent>
	);
};

export default Memory;
